### ISSUE TITLE
Inherit from eslint-config-wikimedia?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-config-node-services#2]
I'd have thought that, ideally, we should inherit as much as possible as explain why we differ where we do (beyond the obvious things like environmental browser vs. node settings).

**Comment by Pchelolo** [comment]
@jdforrester I was thinking about exploring this idea too. Why did I go with the custom config in the first place - I didn't want to put a lot of effort into fixing up the code we've already had and adopt eslint easier, so I've generated the config that's as close to our code style at the time as possible.

I think it totally worths investigating whether it worths inheriting, and it probably is. But it's also possible that it doesn't, because we use ES6 almost everywhere already, nde has some differences from frontend etc. I'll try to run ESLint on backend code tomorrow to see how much we've diverged and will post some data.

**Comment by Pchelolo** [comment]
@jdforrester So, I've tested inheriting from `wikimedia` config, and it's like 1087 errors for just one service. Seems like our frontend and backend JS code is already really different, so I don't think it worths rewriting all the services.
