### ISSUE TITLE
Clarify the need for new coding style than eslint-config-wikimedia

### ISSUE THREAD

**Issue by santhoshtr** [wikimedia/eslint-config-node-services#26]
MediaWiki and WMF extensions use https://github.com/wikimedia/eslint-config-wikimedia. For consistancy cxserver node service also use the same, so that developers need not switch between different styles.

https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript also recommends the above style.

Please clarify why we need 2 styles.

Also the name of this node module is confusing for an outside node developer. It may be better to have wikimedia or wmf in the module name.

+cc @jdforrester

**Comment by Pchelolo** [comment]
The biggest difference is that `eslint-config-wikimedia` was designed for the frontend JavaScript while this one is supposed to cover backend JavaScript, which, obviously, have differences. 

In the beginning in attempt to introduce ESLint to services as quickly and painlessly as possible, we've generated this config so that it matched existing coding practices in all existing services. After that, we're trying to gradually make both configs converge as close as possible ( see #18 #19 #20 #21 #22 ) but it's not a highest priority as every change potentially requires a lot of changes to be done in individual services that are using the config. As this work is done on spare time capacity, it's not moving too fast. 

And in the end even if we converge as close as possible, backend JS might still have some differences in code style left.

**Comment by santhoshtr** [comment]
Good to know that the plan is to converge.  CXServer is already following wikimedia style(https://github.com/wikimedia/mediawiki-services-cxserver/blob/master/.eslintrc.json)
